export const GET_IS_AUTHENTICATED = 'GET_IS_AUTHENTICATED';
export const SET_AUTH = 'SET_AUTH';
export const GET_SPINNER_STATUS = 'GET_SPINNER_STATUS';
export const SET_SPINNER_STATUS = 'SET_SPINNER_STATUS';
